name: liveness_flutter
description: >-
  Plug-and-play liveness detection for Flutter. Configure action sequences like blink and smile, capture images or video, and send verification results to your backend.
version: 0.4.3
homepage: https://github.com/maykhid/liveness_flutter
repository: https://github.com/maykhid/liveness_flutter

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.12.0+2
  google_mlkit_face_detection: ^0.14.0
  image: ^4.3.0
  http: ^1.2.0
  screen_brightness: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
